[%
    T = {
        configure_1                                = "IntranetUserJS: SearchHelpers Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: SearchHelpers &rsaquo; Configuration",
        configure_5                                = "Hakusanastot:",
        configure_6                                = "(a space-separated list of search terms, e.g. \"yso allars finaf\")",
        configure_7                                = "Save",
    }
%]
