[%
    T = {
        configure_1                                = "IntranetUserJS: Search assistant",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Search assistant &rsaquo; Configuration",
        configure_5                                = "Vocabularies:",
        configure_6                                = "(a space-separated list of vocabularies, e.g. \"yso allars finaf\")",
        configure_7                                = "Save",
    }
%]
