[%
    T = {
        configure_1                                = "IntranetUserJS: Hakuapuri",
        configure_2                                = "Koti",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: Hakuapuri &rsaquo; Konfiguraatio",
        configure_5                                = "Sanastot: ",
        configure_6                                = "(välilyönnillä eroteltu lista sanastoista, esim. \"yso allars finaf\")",
        configure_7                                = "Tallenna",
    }
%]
