[%
    T = {
        configure_1                                = "IntranetUserJS: SearchHelpers Konfiguraatio",
        configure_2                                = "Koti",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: SearchHelpers &rsaquo; Konfiguraatio",
        configure_5                                = "Hakusanat:",
        configure_6                                = "(välilyönnillä eroteltu lista hakusanoista, esim. \"yso allars finaf\")",
        configure_7                                = "Tallenna",
    }
%]
