[%
    T = {
        configure_1                                = "IntranetUserJS: SearchHelpers Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Moduler",
        configure_4                                = "&rsaquo; IntranetUserJS: SearchHelpers &rsaquo; Konfiguration",
        configure_5                                = "Sökordlistor:",
        configure_6                                = "(välilyönnillä eroteltu lista hakusanastoista, esim. \"yso allars finaf\")",
        configure_7                                = "Spara",
    }
%]
