[%
    T = {
        configure_1                                = "IntranetUserJS: Sökassistent",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Sökassistent &rsaquo; Konfiguration",
        configure_5                                = "Vokabulärer:",
        configure_6                                = "(lista över vokabulärer, åtskilda med mellanslag, \"yso allars finaf\")",
        configure_7                                = "Spara",
    }
%]
